//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGramaticaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GramaticaBaseListener : IGramaticaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] GramaticaParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] GramaticaParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.pg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPg([NotNull] GramaticaParser.PgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.pg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPg([NotNull] GramaticaParser.PgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.sl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSl([NotNull] GramaticaParser.SlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.sl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSl([NotNull] GramaticaParser.SlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterS([NotNull] GramaticaParser.SContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitS([NotNull] GramaticaParser.SContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.d"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterD([NotNull] GramaticaParser.DContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.d"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitD([NotNull] GramaticaParser.DContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE([NotNull] GramaticaParser.EContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE([NotNull] GramaticaParser.EContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEp([NotNull] GramaticaParser.EpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEp([NotNull] GramaticaParser.EpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterT([NotNull] GramaticaParser.TContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitT([NotNull] GramaticaParser.TContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.tp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTp([NotNull] GramaticaParser.TpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.tp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTp([NotNull] GramaticaParser.TpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.f"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF([NotNull] GramaticaParser.FContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.f"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF([NotNull] GramaticaParser.FContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ds"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDs([NotNull] GramaticaParser.DsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ds"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDs([NotNull] GramaticaParser.DsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.dsp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDsp([NotNull] GramaticaParser.DspContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.dsp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDsp([NotNull] GramaticaParser.DspContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.io"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIo([NotNull] GramaticaParser.IoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.io"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIo([NotNull] GramaticaParser.IoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ce"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCe([NotNull] GramaticaParser.CeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ce"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCe([NotNull] GramaticaParser.CeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ifd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfd([NotNull] GramaticaParser.IfdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ifd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfd([NotNull] GramaticaParser.IfdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEd([NotNull] GramaticaParser.EdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEd([NotNull] GramaticaParser.EdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.edp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEdp([NotNull] GramaticaParser.EdpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.edp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEdp([NotNull] GramaticaParser.EdpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.fd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFd([NotNull] GramaticaParser.FdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.fd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFd([NotNull] GramaticaParser.FdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.rt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRt([NotNull] GramaticaParser.RtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.rt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRt([NotNull] GramaticaParser.RtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.pl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPl([NotNull] GramaticaParser.PlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.pl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPl([NotNull] GramaticaParser.PlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.plp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlp([NotNull] GramaticaParser.PlpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.plp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlp([NotNull] GramaticaParser.PlpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTy([NotNull] GramaticaParser.TyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTy([NotNull] GramaticaParser.TyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.typ"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTyp([NotNull] GramaticaParser.TypContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.typ"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTyp([NotNull] GramaticaParser.TypContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.fc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFc([NotNull] GramaticaParser.FcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.fc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFc([NotNull] GramaticaParser.FcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.p"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterP([NotNull] GramaticaParser.PContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.p"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitP([NotNull] GramaticaParser.PContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.pp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPp([NotNull] GramaticaParser.PpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.pp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPp([NotNull] GramaticaParser.PpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
