//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] GramaticaParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] GramaticaParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.pg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPg([NotNull] GramaticaParser.PgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.pg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPg([NotNull] GramaticaParser.PgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.sl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSl([NotNull] GramaticaParser.SlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.sl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSl([NotNull] GramaticaParser.SlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS([NotNull] GramaticaParser.SContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS([NotNull] GramaticaParser.SContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterD([NotNull] GramaticaParser.DContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitD([NotNull] GramaticaParser.DContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterE([NotNull] GramaticaParser.EContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitE([NotNull] GramaticaParser.EContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEp([NotNull] GramaticaParser.EpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEp([NotNull] GramaticaParser.EpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT([NotNull] GramaticaParser.TContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT([NotNull] GramaticaParser.TContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.tp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTp([NotNull] GramaticaParser.TpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.tp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTp([NotNull] GramaticaParser.TpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.f"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF([NotNull] GramaticaParser.FContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.f"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF([NotNull] GramaticaParser.FContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDs([NotNull] GramaticaParser.DsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDs([NotNull] GramaticaParser.DsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.dsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDsp([NotNull] GramaticaParser.DspContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.dsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDsp([NotNull] GramaticaParser.DspContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.io"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIo([NotNull] GramaticaParser.IoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.io"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIo([NotNull] GramaticaParser.IoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ce"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCe([NotNull] GramaticaParser.CeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ce"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCe([NotNull] GramaticaParser.CeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ifd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfd([NotNull] GramaticaParser.IfdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ifd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfd([NotNull] GramaticaParser.IfdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEd([NotNull] GramaticaParser.EdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEd([NotNull] GramaticaParser.EdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.edp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEdp([NotNull] GramaticaParser.EdpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.edp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEdp([NotNull] GramaticaParser.EdpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.fd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFd([NotNull] GramaticaParser.FdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.fd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFd([NotNull] GramaticaParser.FdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.rt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRt([NotNull] GramaticaParser.RtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.rt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRt([NotNull] GramaticaParser.RtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.pl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPl([NotNull] GramaticaParser.PlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.pl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPl([NotNull] GramaticaParser.PlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.plp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlp([NotNull] GramaticaParser.PlpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.plp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlp([NotNull] GramaticaParser.PlpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.ty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTy([NotNull] GramaticaParser.TyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.ty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTy([NotNull] GramaticaParser.TyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyp([NotNull] GramaticaParser.TypContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyp([NotNull] GramaticaParser.TypContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.fc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFc([NotNull] GramaticaParser.FcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.fc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFc([NotNull] GramaticaParser.FcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterP([NotNull] GramaticaParser.PContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitP([NotNull] GramaticaParser.PContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GramaticaParser.pp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPp([NotNull] GramaticaParser.PpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GramaticaParser.pp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPp([NotNull] GramaticaParser.PpContext context);
}
