//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GramaticaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGramaticaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] GramaticaParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.pg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPg([NotNull] GramaticaParser.PgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.sl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSl([NotNull] GramaticaParser.SlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitS([NotNull] GramaticaParser.SContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitD([NotNull] GramaticaParser.DContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitE([NotNull] GramaticaParser.EContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.ep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEp([NotNull] GramaticaParser.EpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitT([NotNull] GramaticaParser.TContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.tp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTp([NotNull] GramaticaParser.TpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.f"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF([NotNull] GramaticaParser.FContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.ds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDs([NotNull] GramaticaParser.DsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.dsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDsp([NotNull] GramaticaParser.DspContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.io"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIo([NotNull] GramaticaParser.IoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.ce"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCe([NotNull] GramaticaParser.CeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.ifd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfd([NotNull] GramaticaParser.IfdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.ed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEd([NotNull] GramaticaParser.EdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.edp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdp([NotNull] GramaticaParser.EdpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.fd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFd([NotNull] GramaticaParser.FdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.rt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRt([NotNull] GramaticaParser.RtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.pl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPl([NotNull] GramaticaParser.PlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.plp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlp([NotNull] GramaticaParser.PlpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.ty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTy([NotNull] GramaticaParser.TyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTyp([NotNull] GramaticaParser.TypContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.fc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFc([NotNull] GramaticaParser.FcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitP([NotNull] GramaticaParser.PContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramaticaParser.pp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPp([NotNull] GramaticaParser.PpContext context);
}
